version: "3.9"

services:

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    container_name: sport_shop_postgres
    restart: "on-failure"

  api:
    build: .
    entrypoint: /api.sh
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - 2222:2222
    container_name: sport_shop_api
    restart: "on-failure"

  nginx:
    depends_on:
      - api
    build: nginx
    ports:
      - 1300:80
    volumes:
      - media_volume:/sportShop/media
    container_name: sport_shop_nginx
    restart: "on-failure"

  redis:
    image: redis
    container_name: sport_shop_redis
    ports:
      - 6379:6379
    restart: "on-failure"

  celery:
    build: .
    entrypoint: /celery.sh
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/sportShop
    ports:
      - 8787:8787
    container_name: sport_shop_celery
    restart: "on-failure"

  celery-beat:
    build: .
    entrypoint: /celery-beat.sh
    depends_on:
      - postgres
      - redis
    ports:
      - 8989:8989
    volumes:
      - .:/sportShop
    container_name: sport_shop_celery_beat
    restart: "on-failure"

volumes:
  postgres_data:
  media_volume:
