version: "3.9"

services:

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c log_statement=all
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${DB_PORT}
    container_name: sport_shop_postgres
    restart: "on-failure"

  api:
    build: .
    entrypoint: /api.sh
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - sport_shop_volume:/sportShop
    container_name: sport_shop_api
    restart: "on-failure"

  nginx:
    depends_on:
      - api
    build: nginx
    ports:
      - 1300:80
    volumes:
      - media_volume:/sportShop/media
    container_name: sport_shop_nginx
    restart: "on-failure"

  redis:
    build: redis
    volumes:
      - redis_volume:/data
    container_name: sport_shop_redis
    restart: "on-failure"

  celery:
    build: .
    entrypoint: /celery.sh
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/sportShop
    user: sport_shop_user:sport_shop_group
    container_name: sport_shop_celery
    restart: always

  celery-beat:
    build: .
    entrypoint: /celery-beat.sh
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/sportShop
    user: sport_shop_user:sport_shop_group
    container_name: sport_shop_celery_beat
    restart: always

volumes:
  postgres_data:
  media_volume:
  sport_shop_volume:
  redis_volume:
