version: "3.9"

services:

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${DB_PORT}
    restart: "on-failure"

  api:
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: "on-failure"

  nginx:
    depends_on:
      - api
    build: nginx
    ports:
      - 1300:80
    volumes:
      - media_volume:${APIDIR}/media
    restart: "on-failure"

  redis:
    image: redis

  celery:
    build: celery
    depends_on:
      - redis

  celery-beat:
    build: celery-beat
    depends_on:
      - redis

volumes:
  postgres_data:
  media_volume:
